=== tiasmaulanaa/tugasxsddanprak/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Perkantoran">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamat"/>
                <xs:element ref="email"/>
                <xs:element ref="gaji"/>
                <xs:element ref="id_karyawan"/>
                <xs:element ref="kantor"/>
                <xs:element ref="nama_belakang"/>
                <xs:element ref="nama_depan"/>
                <xs:element ref="no_tlpn"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="tanggal_perekrutan"/>
            </xs:choice>
            <xs:attribute name="Data" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="gaji">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="satuan" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="id_karyawan" type="xs:integer"/>
    <xs:element name="kantor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alamat"/>
            </xs:sequence>
            <xs:attribute name="nama" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama_belakang" type="xs:NCName"/>
    <xs:element name="nama_depan" type="xs:NCName"/>
    <xs:element name="no_tlpn" type="xs:integer"/>
    <xs:element name="pekerjaan" type="xs:string"/>
    <xs:element name="tanggal_perekrutan" type="xs:string"/>
    <xs:element name="alamat" type="xs:string"/>
</xs:schema>

=== tiasmaulanaa/tugasxsddanprak/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<Perkantoran Data="Karyawan" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employees.xsd">
	
	<id_karyawan>101</id_karyawan>
	<nama_depanTias</nama_depan>
	<nama_belakang>Maulana</nama_belakang>
	<alamat>Jakarta</alamat>
	<email>tiasmaulanaa@gmail.com</email>
	<no_tlpn>+6287863892031</no_tlpn>
	<tanggal_perekrutan>5 September 2009</tanggal_perekrutan>
	<pekerjaan>President</pekerjaan>
	<gaji satuan="dolar">24000</gaji>
	<kantor nama="PT.INDAH PERMANA">
		<alamat>Jl. Gatot Subroto No.43</alamat>
	</kantor>
	
	<id_karyawan>102</id_karyawan>
	<nama_depan>Rikma</nama_depan>
	<nama_belakang>Nurhadi</nama_belakang>
	<alamat>Jakarta</alamat>
	<email>rikma_nurhadi@gmail.com</email>
	<no_tlpn>+6282113409971</no_tlpn>
	<tanggal_perekrutan>11 Oktober 2009</tanggal_perekrutan>
	<pekerjaan>Programmer</pekerjaan>
	<gaji satuan="dolar">9000</gaji>
	<kantor nama="PT.INDAH PERMANA">
		<alamat>Jl. Gatot Subroto No.43</alamat>
	</kantor>
	
	<id_karyawan>103</id_karyawan>
	<nama_depan>Diki</nama_depan>
	<nama_belakang>Wahyu</nama_belakang>
	<alamat>Bandungbarat</alamat>
	<email>dikiwahyu0@gmail.com</email>
	<no_tlpn>+6282110293823</no_tlpn>
	<tanggal_perekrutan>5 Januari 2010</tanggal_perekrutan>
	<pekerjaan>Finance Manager</pekerjaan>
	<gaji satuan="dolar">12008</gaji>
	<kantor nama="PT.INDAH PERMANA">
		<alamat>Jl. Gatot Subroto No.43</alamat>
	</kantor>
	
	<id_karyawan>104</id_karyawan>
	<nama_depan>Muhammad</nama_depan>
	<nama_belakang>lutfhi</nama_belakang>
	<alamat>Bandung</alamat>
	<email>muhluthfi@gmail.com</email>
	<no_tlpn>+6282329381719</no_tlpn>
	<tanggal_perekrutan>3 Desember 2009</tanggal_perekrutan>
	<pekerjaan>Sales Manager</pekerjaan>
	<gaji satuan="dolar">11000</gaji>
	<kantor nama="PT.INDAH PERMANA">
		<alamat>Jl. Gatot Subroto No.43</alamat>
	</kantor>
	
	<id_karyawan>105</id_karyawan>
	<nama_depan>Angela</nama_depan>
	<nama_belakang>caramoy</nama_belakang>
	<alamat>Medan</alamat>
	<email>Angela11@gmail.com</email>
	<no_tlpn>+6285620001291</no_tlpn>
	<tanggal_perekrutan>21 Februari 2010</tanggal_perekrutan>
	<pekerjaan>Accounting</pekerjaan>
	<gaji satuan="dolar">8200</gaji>
	<kantor nama="PT.INDAH PERMANA">
		<alamat>Jl. Gatot Subroto No.43</alamat>
	</kantor>
	
</Perkantoran>
